### ISSUE TITLE
Does not deploy

### ISSUE THREAD

**Issue by carrollh** [aws-quickstart/quickstart-microsoft-sql#4]
templates/sql-master.template: 
lines 737, 814, 888, 911, 967, 1006, and 1053 - missing '/' after ${QSS3KeyPrefix} 
lines 888 and 967 - QSS3KeyPrefix parameter for ad and rdgw modules cannot end in a '/'

templates/sql.template:
line 986 and ~61 more times - missing '/' after ${QSS3KeyPrefix}

**Comment by santiagocardenas** [comment]
Hi Heath,
We moved the S3 Key Prefix's '/' to be explicit in the parameter value itself rather than appending it as it is more transparent to the end-user. In the past, we would _automagically_ append that '/' through an internal Join function, but it forces the end-user to have copied all the templates using a key prefix that ends with a '/'.

For example, if I don't want a '/' at the end, I can use a key prefix that's something like _**my-key-prefix**_ and sync all the Quick Start assets on there. While they won't look like directories to S3 (since it uses the '/' as a directory delimiter), it's still something that is allowed and can be done on S3.

So long-story short, this Quick Start does deploy accordingly as long as the QSS3KeyPrefix value is the actual one, which in the case of the **quickstart-reference** bucket, it's _**microsoft/sql/latest/**_ (notice the '/' at the end).

**Comment by carrollh** [comment]
I thought about that, but then it failed telling me the AD module couldn't take the '/' on the end of the QSS3KeyPrefix parameter. I must've pulled it right before the AD module was updated. Timing.
